import { useState } from 'react'
import Head from 'next/head'
import SeedField from '../components/seed-field'
import SeedList from '../components/seed-list'

export default function Index() {
    const [updatedAt, setUpdatedAt] = useState(Date.now())

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="container mx-auto p-8 space-y-4">
                <SeedField setUpdatedAt={setUpdatedAt} />
                <SeedList setUpdatedAt={setUpdatedAt} updatedAt={updatedAt} />
            </main>
        </>
    )
}
